openapi: 3.0.0
info:
  title: "crud_foto_pessoa"
  description: "crud_foto_pessoa"
  version: "20250406032136"
servers:
  - url: http://localhost:8080/SeletivoSEPLAGHOM/foto_pessoa
paths:
  /Create:
    post:
      tags:
        - crud_foto_pessoa  
      operationId: "crud_foto_pessoa.Create"
      summary: "Create"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"

  /Read_GetList:
    get:
      tags:
        - crud_foto_pessoa  
      operationId: "crud_foto_pessoa.Read_GetList"
      summary: "Read_GetList"
      parameters:
        - name: "Pagenumber"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int64"
        - name: "Pagesize"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int64"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/sdtListaFotoPessoas_sdtListaFotoPessoasItem"  

        404:
          description: "Not found"

  /Read_GetByKey:
    get:
      tags:
        - crud_foto_pessoa  
      operationId: "crud_foto_pessoa.Read_GetByKey"
      summary: "Read_GetByKey"
      parameters:
        - name: "Codgpessoa"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Read_GetByKeyOutput"
        404:
          description: "Not found"

  /Update:
    put:
      tags:
        - crud_foto_pessoa  
      operationId: "crud_foto_pessoa.Update"
      summary: "Update"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"

  /Delete:
    delete:
      tags:
        - crud_foto_pessoa  
      operationId: "crud_foto_pessoa.Delete"
      summary: "Delete"
      parameters:
        - name: "Codfotopessoa"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"
components:
  schemas:
    Read_GetByKeyOutput:
      properties:
        ListaFotos:
          description: "sdt Lista Foto Pessoa"
          $ref: "#/components/schemas/sdtListaFotoPessoa"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"



    CreateInput:  
      properties:
        DadosFotoPessoa:
          description: "sdt Foto Pessoa"
          $ref: "#/components/schemas/sdtFotoPessoa"



    UpdateInput:  
      properties:
        ListaFotoPessoa:
          description: "sdt Atualizar Foto Pessoa"
          $ref: "#/components/schemas/sdtAtualizarFotoPessoa"

  
    sdtFotoPessoa:
      properties:
        pes_id:
          description: "pes_id"
          type: "integer"
          format: "int32"
        foto:
          description: "sdt Foto"
          type: array
          items:
            $ref: "#/components/schemas/sdtFoto"



    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"



    sdtListaFotoPessoas_sdtListaFotoPessoasItem:
      properties:
        pes_id:
          description: "pes_id"
          type: "integer"
          format: "int32"
        pes_nome:
          description: "pes_nome"
          type: "string"
        Foto:
          description: "sdt URLFoto"
          type: array
          items:
            $ref: "#/components/schemas/sdtURLFoto"



    sdtListaFotoPessoa:
      properties:
        pes_id:
          description: "pes_id"
          type: "integer"
          format: "int32"
        pes_nome:
          description: "pes_nome"
          type: "string"
        Foto:
          description: "sdt URLFoto"
          type: array
          items:
            $ref: "#/components/schemas/sdtURLFoto"



    sdtAtualizarFotoPessoa:
      properties:
        pes_id:
          description: "pes_id"
          type: "integer"
          format: "int32"

        foto:
          type: array
          items:
            description: Item
            $ref: "#/components/schemas/sdtAtualizarFotoPessoa.foto_Item"


    sdtAtualizarFotoPessoa.foto_Item:
      properties:
        fp_id:
          description: "ID da foto para atualizar"
          type: "integer"
          format: "int32"
        arquivoBase64NovaFoto:
          description: "arquivo Base64 Nova Foto"
          type: "string"


      x-gx-level: "sdtAtualizarFotoPessoa"

    sdtFoto:
      properties:
        arquivoBase64:
          description: "arquivo Base64"
          type: "string"



    sdtURLFoto:
      properties:
        LinkExp5Minutos:
          description: "Link Exp5 Minutos"
          type: "string"
        fp_id:
          description: "fp_id"
          type: "integer"
          format: "int32"



 
